
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432